/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmgmt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ojaswi Kumar
 */
public class Roomates extends javax.swing.JFrame {

    /**
     * Creates new form Roomates
     */
    static Connection conn1;
    static String selfno;
    static String Regno;
    
    public Roomates(String registerno) {
        initComponents();
        conn1 = null;
        Regno=registerno;
        
        try 
        {
            String url1 = "jdbc:mysql://localhost:3306/hostel_management_system";
            String user = "root";
            String password = "root";
            conn1 = DriverManager.getConnection(url1, user, password);
            try{
            if (conn1 != null) 
            {
                //System.out.println("Connected to the database test1");
                String sql = "SELECT roomAlloted,blockalloted FROM student where registerno=\"" + Regno + "\"" + ";";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                int count = 0;
                String Block="";
                int roomnumber=0;
                while (result.next())
                {
                    roomnumber=result.getInt("RoomAlloted");
                    Block = result.getString("BlockAlloted");
                    //System.out.printf("%s - %d",Block, roomnumber);
                }
                String sql1 = "SELECT RegisterNo,FirstName,LastName,Branch from student where blockAlloted = \"" + Block + "\" and roomalloted=\"" + roomnumber + "\";";
                statement = conn1.createStatement();
                ResultSet result2 = statement.executeQuery(sql1);
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); 
                while(result2.next())
                {
                    String fname = result2.getString("FirstName");
                    String lname = result2.getString("LastName");
                    String regnum = result2.getString("Registerno");
                    String branch = result2.getString("Branch");
                    //System.out.printf("%s - %s - %s - %s\n",fname,lname,regnum,branch);
                    model.addRow(new Object[]{regnum,fname+" "+lname,branch});
                }
            }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REG NO.", "NAME", "BRANCH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("The persons in your room are:");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roomates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roomates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roomates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roomates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql = "SELECT * FROM student where registerno=\"" + Regno + "\"" + ";";
                Statement statement = conn1.createStatement();
            ResultSet result = statement.executeQuery(sql);
            String block="";
            int roomno;
            while (result.next())
            {
                roomno = result.getInt("RoomAlloted");
                block = result.getString("BlockAlloted");
                //System.out.printf("%d\t%s",roomno,block);
            }
        }
        }catch(SQLException ex)
        {
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roomates(selfno).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
